### ISSUE TITLE
SSL Error Handler

### ISSUE THREAD

**Issue by cschellhas** [OpenCMP-net/cmp-android#1]
Running into the following issue:

https://support.google.com/faqs/answer/7071387

I think it is related to this part:

https://github.com/opencmp/cmp-android/blob/6fbc0732f6ab498915c2a4f25fd46bf573cf8611/opencmplib/src/main/java/com/opencmp/inapplib/OpenCmpWebviewClient.java#L32-L36

**Comment by andireuter** [comment]
Hi @cschellhas. Thanks for reporting this issue. We will fix the issue soon.

**Comment by andireuter** [comment]
Now a 'toast' shows up to inform about the SSL error. SSL errors are no longer forcibly skipped in the handler.
